name: youtube_api
description: "A Flutter package for extracting downloadable video URLs from YouTube videos. Supports multiple video qualities including HD formats."
version: 1.0.5
homepage: https://github.com/yourusername/youtube_api
repository: https://github.com/yourusername/youtube_api
issue_tracker: https://github.com/yourusername/youtube_api/issues

# Ignore false positives for API keys that are not actual secrets
false_secrets:
  - "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8"
  - "AIzaSyA8eiZmM1FaDVjRy-df2KTyQ_vz_yYM39w"

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  html: ^0.15.0
  webview_flutter: ^4.4.0
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
